// export const STEPS = [
//   { key: "prep", titleFa: "آماده‌سازی: ست خون و صافی را نصب کنید", hintEn: "Load bloodlines & dialyzer on the machine.", detailsFa: "ست شریانی و وریدی را روی پمپ و پایه‌ها قرار دهید. صافی (دیالایزر) را عمودی نصب کنید. همه کلمپ‌ها بسته باشند.", highlights: ["dialyzer", "pump", "lines"] },
//   { key: "saline", titleFa: "اتصال سالین: نرمال سالین را به لاین شریانی وصل کنید", hintEn: "Spike arterial line into NS bag; hang bag.", detailsFa: "ست شریانی را به سرم وصل و آویزان کنید. کلمپ نزدیک اسپایک را باز کنید. محفظه شریانی تا نصف پر شود.", highlights: ["saline", "arterial", "artChamber"] },
//   { key: "primeArt", titleFa: "پرایم اولیه: پمپ خون را آرام راه‌اندازی کنید", hintEn: "Start blood pump ~150 mL/min to fill lines.", detailsFa: "پمپ خون را روی حدود 100 mL/min بگذارید. کلمپ‌های مسیر شریانی را باز کنید تا مسیر تا صافی پر شود و حباب‌ها خارج شوند.", highlights: ["pump", "arterial", "dialyzer"] },
//   { key: "primeDialyzer", titleFa: "پرایم صافی: صافی را از پایین به بالا پر کنید", hintEn: "Fill dialyzer bottom→top; tap to release bubbles.", detailsFa: "اجازه دهید مایع از ورودی پایین صافی وارد و از بالا خارج شود. به بدنه صافی ضربه بزنید تا حباب‌ها جدا شوند.", highlights: ["dialyzer"] },
//   { key: "primeVen", titleFa: "مسیر وریدی: محفظه وریدی را در محل خود و تا خط علامت پر کنید", hintEn: "Fill venous chamber to line; check for air.", detailsFa: "جریان را ادامه دهید تا محفظه وریدی تا خط مشخص پر شود. پیچ هواگیری را باز و بسته کنید تا حباب‌ها خارج شوند.", highlights: ["venous", "venChamber"] },
//   { key: "recirc", titleFa: "سیرکولاسیون: انتهای وریدی را به سالین برگردانید", hintEn: "Recirculate venous return back to bag until clear.", detailsFa: "انتهای لاین وریدی را موقتاً به کیسه سالین برگردانید و چند دقیقه گردش دهید تا هیچ حبابی دیده نشود.", highlights: ["venous", "saline"] },
//   { key: "ready", titleFa: "پایان پرایم: کلمپ‌ها را ببندید و آماده اتصال به بیمار", hintEn: "Clamp, stop pump, connect to patient per protocol.", detailsFa: "پمپ را متوقف و کلمپ‌ها را مطابق پروتکل ببندید/باز کنید. مسیرها را بررسی کنید. دستگاه برای اتصال آماده است.", highlights: ["all"] },
// ];
