export const filters = [
  {
    name: "F4",
    suitableFor: "<15 کیلوگرم",
    description: "صافی کوچک مناسب برای نوزاد و کودک کم‌وزن",
    minWeight: 0,
    maxWeight: 14.9,
    koa: "2.8 mL/min",
    uf: "364 mL/min",
    tmp: "600 mmHg",
    preferredForUnstable: true,
  },
  {
    name: "F6",
    suitableFor: "15–20 کیلوگرم",
    description: "توان پاکسازی متوسط؛ فشار مناسب",
    minWeight: 15,
    maxWeight: 20,
    koa: "5.5 mL/min",
    uf: "630 mL/min",
    tmp: "600 mmHg",
    preferredForUnstable: true,
  },
  {
    name: "PS10",
    suitableFor: "15–25 کیلوگرم",
    description: "مناسب برای کودکان با وزن متوسط رو به بالا",
    minWeight: 15,
    maxWeight: 25,
    koa: "6.8 mL/min",
    uf: "637 mL/min",
    tmp: "500 mmHg",
    preferredForUnstable: false,
  },
  {
    name: "PS13",
    suitableFor: "20–40 کیلوگرم",
    description: "قابل استفاده برای کودکان بزرگ‌تر",
    minWeight: 20,
    maxWeight: 40,
    koa: "8.8 mL/min",
    uf: "746 mL/min",
    tmp: "500 mmHg",
    preferredForUnstable: false,
  },
];